### ISSUE TITLE
 download the annotation of ExDark

### ISSUE THREAD

**Issue by Egolee0713** [surajpaib/Low-Light-Enhancement#2]
I can not download the annotation of ExDark by this link:https://drive.google.com/file/d/1goqzN0Eg7YqClZfP3cQ9QjENFrEhildz/view?usp=sharing

It would be very nice if you can provide another link to download.

**Comment by surajpaib** [comment]
Hi @yongjingli 

It should be shared with everyone so shouldn't be an access related problem right? What exactly is the problem you are facing?

**Comment by Egolee0713** [comment]
@surajpaib  It could not download by the link yesterday, but it works well today, thank you for your kind answer.
